#!/usr/bin/env bash
ThePath=$1
TheBinDir=$2

if [ ! -z "${ThePath}" ] && [ -d "${ThePath}" ]; then
	PomFile=${ThePath}/pom.xml
	if [ ! -z "${ThePath}" ] && [ -f "${PomFile}" ]; then
		cd ${ThePath}/
		mvn clean install
		cd - > /dev/null
	fi
fi
