#!/usr/bin/env bash
ThePath=$1
TheSrcFile=$2
if [ ! -z "${ThePath}" ] && [ -d "${ThePath}" ] && [ ! -z "${TheSrcFile}" ]; then
	TheNewSrcFile=$(find -L ${ThePath} -name ${TheSrcFile} 2> /dev/null)
	if [ ! -z "${TheNewSrcFile}" ] && [ -f "${TheNewSrcFile}" ]; then
		echo ${TheNewSrcFile}
	fi
fi
